name: npm-test
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        include:
          # - os: windows-latest # snapshots are different on Windows, so this should be disabled
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: PNPM install
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
    - run: xvfb-run -a npm test
      working-directory: ./vscode-extension
      if: runner.os == 'Linux'
    - run: npm test
      working-directory: ./vscode-extension
      if: runner.os != 'Linux'
